Disfraces/src/java/jsf/AdminController.java
package jsf;

import entidad.Admin;
import jsf.util.JsfUtil;
import jsf.util.PaginationHelper;
import session.AdminFacade;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.ResourceBundle;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;

@ManagedBean(name = "adminController")
@SessionScoped
public class AdminController implements Serializable {

    private Admin current;
    private DataModel items = null;
    @EJB
    private session.AdminFacade ejbFacade;
    private PaginationHelper pagination;
    private int selectedItemIndex;

    public AdminController() {
    }
    
    public String login() {
        //current es lo leido del form
        //a es lo consultado
        Admin a;
        a = (Admin) getItems().getRowData();
        for(int i = 0; i < getItems().getRowCount(); i++){
            if(a.getEmail().equalsIgnoreCase(current.getEmail())){
                break;
            }else{
                getItems().setRowIndex(i+1);
                a = (Admin) getItems().getRowData();
            }
        }
        System.out.println("---------------------");
        System.out.println(a.getEmail());
        System.out.println(a.getPassword());
        System.out.println(a.getNombre());
        System.out.println("-    -    -    -    -");
        System.out.println(current.getEmail());
        System.out.println(current.getPassword());
        System.out.println(current.getNombre());
        System.out.println("---------------------");
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        if(a.getPassword().equals(current.getPassword())){
            current.setNombre(a.getNombre());
            current.setApellidos(a.getApellidos());
            current.setTipo(a.getTipo());
            if(a.getTipo()==1){
                return "admin";
            }else{
                return "empleado";
            }
        }else{
            return "intruso";
        }
    }

    public Admin buscar(String user, String password){
//        items = ejbFacade.find(user);
        System.out.println("Aqui tambien");
        ejbFacade = new AdminFacade();
        Admin a = ejbFacade.find(user);
        
        System.out.println("Aqui pasa");
        if(a != null){
            if(a.getEmail() == user & a.getPassword() == password){
                return a;
            }else{
                return null;
            }
        }else{
            return null;
        }
    }

    public Admin getSelected() {
        if (current == null) {
            current = new Admin();
            selectedItemIndex = -1;
        }
        return current;
    }

    private AdminFacade getFacade() {
        return ejbFacade;
    }

    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(10) {
                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public DataModel createPageDataModel() {
                    return new ListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem() + getPageSize()}));
                }
            };
        }
        return pagination;
    }

    public String prepareList() {
        recreateModel();
        return "List";
    }

    public String prepareView() {
        current = (Admin) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "View";
    }

    public String prepareCreate() {
        current = new Admin();
        selectedItemIndex = -1;
        return "Create";
    }

    public String create() {
        try {
            getFacade().create(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/resources/Bundle").getString("AdminCreated"));
            return prepareCreate();
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/resources/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String prepareEdit() {
        current = (Admin) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "Edit";
    }

    public String update() {
        try {
            getFacade().edit(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/resources/Bundle").getString("AdminUpdated"));
            return "View";
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/resources/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String destroy() {
        current = (Admin) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        performDestroy();
        recreatePagination();
        recreateModel();
        return "List";
    }

    public String destroyAndView() {
        performDestroy();
        recreateModel();
        updateCurrentItem();
        if (selectedItemIndex >= 0) {
            return "View";
        } else {
            // all items were removed - go back to list
            recreateModel();
            return "List";
        }
    }

    private void performDestroy() {
        try {
            getFacade().remove(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/resources/Bundle").getString("AdminDeleted"));
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/resources/Bundle").getString("PersistenceErrorOccured"));
        }
    }

    private void updateCurrentItem() {
        int count = getFacade().count();
        if (selectedItemIndex >= count) {
            // selected index cannot be bigger than number of items:
            selectedItemIndex = count - 1;
            // go to previous page if last page disappeared:
            if (pagination.getPageFirstItem() >= count) {
                pagination.previousPage();
            }
        }
        if (selectedItemIndex >= 0) {
            current = getFacade().findRange(new int[]{selectedItemIndex, selectedItemIndex + 1}).get(0);
        }
    }

    public DataModel getItems() {
        if (items == null) {
            items = getPagination().createPageDataModel();
        }
        return items;
    }

    private void recreateModel() {
        items = null;
    }

    private void recreatePagination() {
        pagination = null;
    }

    public String next() {
        getPagination().nextPage();
        recreateModel();
        return "List";
    }

    public String previous() {
        getPagination().previousPage();
        recreateModel();
        return "List";
    }

    public SelectItem[] getItemsAvailableSelectMany() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), false);
    }

    public SelectItem[] getItemsAvailableSelectOne() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), true);
    }

    @FacesConverter(forClass = Admin.class)
    public static class AdminControllerConverter implements Converter {

        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            AdminController controller = (AdminController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "adminController");
            return controller.ejbFacade.find(getKey(value));
        }

        java.lang.String getKey(String value) {
            java.lang.String key;
            key = value;
            return key;
        }

        String getStringKey(java.lang.String value) {
            StringBuffer sb = new StringBuffer();
            sb.append(value);
            return sb.toString();
        }

        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Admin) {
                Admin o = (Admin) object;
                return getStringKey(o.getEmail());
            } else {
                throw new IllegalArgumentException("object " + object + " is of type " + object.getClass().getName() + "; expected type: " + Admin.class.getName());
            }
        }
    }
}

Disfraces/web/admin/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.CreateAdminTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.CreateAdminLabel_nombre}" for="nombre" />
                    <h:inputText id="nombre" value="#{adminController.selected.nombre}" title="#{bundle.CreateAdminTitle_nombre}" required="true" requiredMessage="#{bundle.CreateAdminRequiredMessage_nombre}"/>
                    <h:outputLabel value="#{bundle.CreateAdminLabel_apellidos}" for="apellidos" />
                    <h:inputText id="apellidos" value="#{adminController.selected.apellidos}" title="#{bundle.CreateAdminTitle_apellidos}" required="true" requiredMessage="#{bundle.CreateAdminRequiredMessage_apellidos}"/>
                    <h:outputLabel value="#{bundle.CreateAdminLabel_email}" for="email" />
                    <h:inputText id="email" value="#{adminController.selected.email}" title="#{bundle.CreateAdminTitle_email}" required="true" requiredMessage="#{bundle.CreateAdminRequiredMessage_email}"/>
                    <h:outputLabel value="#{bundle.CreateAdminLabel_password}" for="password" />
                    <h:inputText id="password" value="#{adminController.selected.password}" title="#{bundle.CreateAdminTitle_password}" required="true" requiredMessage="#{bundle.CreateAdminRequiredMessage_password}"/>
                    <h:outputLabel value="#{bundle.CreateAdminLabel_tipo}" for="tipo" />
                    <h:inputText id="tipo" value="#{adminController.selected.tipo}" title="#{bundle.CreateAdminTitle_tipo}" required="true" requiredMessage="#{bundle.CreateAdminRequiredMessage_tipo}"/>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{adminController.create}" value="#{bundle.CreateAdminSaveLink}" />
                <br />
                <br />
                <h:commandLink action="#{adminController.prepareList}" value="#{bundle.CreateAdminShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.CreateAdminIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

Disfraces/web/admin/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.EditAdminTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.EditAdminLabel_nombre}" for="nombre" />
                    <h:inputText id="nombre" value="#{adminController.selected.nombre}" title="#{bundle.EditAdminTitle_nombre}" required="true" requiredMessage="#{bundle.EditAdminRequiredMessage_nombre}"/>
                    <h:outputLabel value="#{bundle.EditAdminLabel_apellidos}" for="apellidos" />
                    <h:inputText id="apellidos" value="#{adminController.selected.apellidos}" title="#{bundle.EditAdminTitle_apellidos}" required="true" requiredMessage="#{bundle.EditAdminRequiredMessage_apellidos}"/>
                    <h:outputLabel value="#{bundle.EditAdminLabel_email}" for="email" />
                    <h:inputText id="email" value="#{adminController.selected.email}" title="#{bundle.EditAdminTitle_email}" required="true" requiredMessage="#{bundle.EditAdminRequiredMessage_email}"/>
                    <h:outputLabel value="#{bundle.EditAdminLabel_password}" for="password" />
                    <h:inputText id="password" value="#{adminController.selected.password}" title="#{bundle.EditAdminTitle_password}" required="true" requiredMessage="#{bundle.EditAdminRequiredMessage_password}"/>
                    <h:outputLabel value="#{bundle.EditAdminLabel_tipo}" for="tipo" />
                    <h:inputText id="tipo" value="#{adminController.selected.tipo}" title="#{bundle.EditAdminTitle_tipo}" required="true" requiredMessage="#{bundle.EditAdminRequiredMessage_tipo}"/>
                </h:panelGrid>
                <h:commandLink action="#{adminController.update}" value="#{bundle.EditAdminSaveLink}"/>
                <br />
                <br />
                <h:link outcome="View" value="#{bundle.EditAdminViewLink}"/>
                <br />
                <h:commandLink action="#{adminController.prepareList}" value="#{bundle.EditAdminShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.EditAdminIndexLink}" />
            </h:form>
        </ui:define>
    </ui:composition>

</html>

Disfraces/web/admin/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="-Titulo-"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:form styleClass="jsfcrud_list_form">
                <h:panelGroup id="messagePanel" layout="block">
                    <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
                </h:panelGroup>
                <h:outputText escape="false" value="-Lista Vacía-" rendered="#{adminController.items.rowCount == 0}"/>
                <h:panelGroup rendered="#{adminController.items.rowCount > 0}">
                    <h:outputText value="#{adminController.pagination.pageFirstItem + 1}..#{adminController.pagination.pageLastItem + 1}/#{adminController.pagination.itemsCount}"/>&nbsp;
                    <h:commandLink action="#{adminController.previous}" value="#{bundle.Previous} #{adminController.pagination.pageSize}" rendered="#{adminController.pagination.hasPreviousPage}"/>&nbsp;
                    <h:commandLink action="#{adminController.next}" value="#{bundle.Next} #{adminController.pagination.pageSize}" rendered="#{adminController.pagination.hasNextPage}"/>&nbsp;
                    <h:dataTable value="#{adminController.items}" var="item" border="0" cellpadding="2" cellspacing="0" rowClasses="jsfcrud_odd_row,jsfcrud_even_row" rules="all" style="border:solid 1px">
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="-Nombre-"/>
                            </f:facet>
                            <h:outputText value="#{item.nombre}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="-Apellidos-"/>
                            </f:facet>
                            <h:outputText value="#{item.apellidos}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="-Mail-"/>
                            </f:facet>
                            <h:outputText value="#{item.email}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="-Password-"/>
                            </f:facet>
                            <h:outputText value="#{item.password}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="-Tipo-"/>
                            </f:facet>
                            <h:outputText value="#{item.tipo}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="&nbsp;"/>
                            </f:facet>
                            <h:commandLink action="#{adminController.prepareView}" value="#{bundle.ListAdminViewLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{adminController.prepareEdit}" value="#{bundle.ListAdminEditLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{adminController.destroy}" value="#{bundle.ListAdminDestroyLink}"/>
                        </h:column>
                    </h:dataTable>
                </h:panelGroup>
                <br />
                <h:commandLink action="#{adminController.prepareCreate}" value="#{bundle.ListAdminCreateLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ListAdminIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

Disfraces/web/admin/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ViewAdminTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputText value="#{bundle.ViewAdminLabel_nombre}"/>
                    <h:outputText value="#{adminController.selected.nombre}" title="#{bundle.ViewAdminTitle_nombre}"/>
                    <h:outputText value="#{bundle.ViewAdminLabel_apellidos}"/>
                    <h:outputText value="#{adminController.selected.apellidos}" title="#{bundle.ViewAdminTitle_apellidos}"/>
                    <h:outputText value="#{bundle.ViewAdminLabel_email}"/>
                    <h:outputText value="#{adminController.selected.email}" title="#{bundle.ViewAdminTitle_email}"/>
                    <h:outputText value="#{bundle.ViewAdminLabel_password}"/>
                    <h:outputText value="#{adminController.selected.password}" title="#{bundle.ViewAdminTitle_password}"/>
                    <h:outputText value="#{bundle.ViewAdminLabel_tipo}"/>
                    <h:outputText value="#{adminController.selected.tipo}" title="#{bundle.ViewAdminTitle_tipo}"/>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{adminController.destroyAndView}" value="#{bundle.ViewAdminDestroyLink}"/>
                <br />
                <br />
                <h:link outcome="Edit" value="#{bundle.ViewAdminEditLink}"/>
                <br />
                <h:commandLink action="#{adminController.prepareCreate}" value="#{bundle.ViewAdminCreateLink}" />
                <br />
                <h:commandLink action="#{adminController.prepareList}" value="#{bundle.ViewAdminShowAllLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ViewAdminIndexLink}"/>

            </h:form>
        </ui:define>
    </ui:composition>

</html>

Disfraces/web/admin/admin.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        <h2>Bienvenido admin #{adminController.selected.nombre}</h2>
        <p style="color:blue;">Seleccione una tarea.</p>
    </h:body>
</html>

Disfraces/web/admin/empleado.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html">
    <h:head>
        <title>Facelet Title</title>
        <link rel="stylesheet" href="css/login.css" />
    </h:head>
    <h:body>
        <h2>Bienvenido empleado #{adminController.selected.nombre}</h2>
        <p style="color:blue;">Seleccione una tarea.</p>
        
    </h:body>
</html>

Disfraces/web/admin/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html">
    <h:head>
        <title>Facelet Title</title>
        <link rel="stylesheet" href="css/login.css" />
    </h:head>
    <h:body>
        <h:form class="formulario">
            <h2>Acceso Administrativo</h2>
            <p>Ingrese sus datos para entrar al sistema.</p>
            <h:panelGrid columns="2">
                <h:outputLabel value="Usuario: " />
                <h:inputText id="user" label="Usuario" required="true" value="#{adminController.selected.email}" />
                <h:outputLabel value="Contraseña: " />
                <h:inputSecret id="password" label="Password" required="true" value="#{adminController.selected.password}" />
            </h:panelGrid>
            <h:messages infoStyle="color: blue;list-style:none;" errorStyle="color:red;list-style:none;"/>
            <section class="seccionBotones">
                <h:commandButton value="Ingresar" class="boton" action="#{adminController.login()}" />
            </section>
        </h:form>
    </h:body>
</html>

Disfraces/web/admin/intruso.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html">
    <h:head>
        <title>Facelet Title</title>
        <link rel="stylesheet" href="css/login.css" />
    </h:head>
    <h:body>
        <h:form class="formulario">
            <h2>Acceso Denegado</h2>
            <p style="color:red;">No ingresó datos de lógin válidos.</p>
        </h:form>
    </h:body>
</html>